name: aahoogendoorn
favicon: null
layout_spectrum: 0.6128457344602793
typography_spectrum: 0.5148189626634121
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4088392606936395
  lightness: 0.6710342688020319
  saturation: 0.6717303439509124
  rhythmicContrast: 0.5707363502588123
purpose: []
